name: CI
on: [push, pull_request]
jobs:
  test:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: ${{ github.head_ref }}

    # Install dependencies
    - uses: pnpm/action-setup@v2.2.2
      with:
        run_install: true

    - name: Test
      run: npm run test

    - name: Save new test results
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Save new test results

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: ${{ github.head_ref }}

    # Install dependencies
    - uses: pnpm/action-setup@v2.2.2
      with:
        run_install: true

    - name: Build
      run: npm run build

    - name: Save new build
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Save new build
